from flask import request
from flask import Blueprint
from domain import appointmentDomain
from flask_jwt_extended import jwt_required
from flask_cors import cross_origin
from utils.authUtil import getUserId

appointment_blueprint = Blueprint('appointment_blueprint', __name__)


@appointment_blueprint.route("/appointments", methods=['POST'])
@cross_origin()
def addAppointmentRequest():
    """
    An API that creates and adds appointment requests to the DB
    ---
    parameters:
       - name: firstName
         in: request
         type: string
         required: true
       - name: lastName
         in: request
         type: string
         required: true
       - name: eventId
         in: request
         type: int
         required: true      
       - name: bookingTimeSlot
         in: request
         type: string
         required: true
       - name: emailId
         in: request
         type: string
         required: true                   
       - name: mobileNumber
         in: request
         type: int
         required: true   
                   
    responses:
        201:
            description: An autogenerated appointment id
            schema:
                id: id
                properties:
                    id:
                        type: int
                        description: The id of the appointment created
                        default: None           
    """            
    data = request.get_json()
    firstName = data.get('firstName', '')
    lastName = data.get('lastName', '')
    eventId = data.get('eventId', 0)
    bookingTimeSlot = data.get('bookingTimeSlot', '')
    emailId = data.get('emailId', '')
    mobileNumber = data.get('mobileNumber', '')

    appointmentId = appointmentDomain.addAppointmentRequest(
        firstName, lastName, eventId, bookingTimeSlot, emailId, mobileNumber)

    return {'id': appointmentId}, 201


@appointment_blueprint.route("/appointments", methods=['GET'])
@jwt_required()
@cross_origin()
def getAllAppointments():
    """
    An API that returns all the appointments stored in the DB
    ---
    responses:
        200:
            description: A list of appointments in the database
            schema:
                id: appointments
                properties:
                    appointments:
                        type: list
                        description: List of appointments in the DB
                        default: None           
    """        
    appointments = appointmentDomain.getAllAppointments()
    return {'appointments': appointments}, 200


@appointment_blueprint.route("/appointments/requested", methods=['GET'])
@jwt_required()
@cross_origin()
def getAllRequestedBookings():
    """
    An API that returns all the appointments with status as requested
    ---
    responses:
        200:
            description: A list of appointments in the database
            schema:
                id: bookings
                properties:
                    bookings:
                        type: list
                        description: List of bookings in the DB
                        default: None           
    """    
    bookings = appointmentDomain.getAllRequestedAppointments()
    return {'bookings': bookings}, 200


@appointment_blueprint.route("/appointments/decline", methods=['PUT'])
@jwt_required()
@cross_origin()
def declineBooking():
    """
    An API that declines a user appointment request
    ---
    parameters:
       - name: appointmentId
         in: request
         type: int
         required: true    
    responses:
        204:
            description: Successfully updated the Appointment          
    """     
    data = request.get_json()
    appointmentId = data.get('appointmentId', 0)

    userId = getUserId()

    updated = appointmentDomain.declineAppointment(appointmentId, userId)

    if updated:
        return 'Successfully updated the Appointment', 204
    return 'Error encountered during Appointment update', 500


@appointment_blueprint.route("/appointments/approve", methods=['PUT'])
@jwt_required()
@cross_origin()
def acceptBooking():
    """
    An API that approves a user appointment request
    ---
    parameters:
       - name: appointmentId
         in: request
         type: int
         required: true    
    responses:
        204:
            description: Successfully updated the Appointment          
    """      
    data = request.get_json()
    appointmentId = data.get('appointmentId', 0)
    userId = getUserId()

    updated = appointmentDomain.acceptAppointment(appointmentId, userId)

    if updated:
        return 'Successfully updated the Appointment', 204
    return 'Error encountered during Appointment update', 500
