from flask import request
from flask import Blueprint
from flask_cors import cross_origin
from domain import customerDomain

customer_blueprint = Blueprint('customer_blueprint', __name__)


@customer_blueprint.route("/customer", methods=['POST'])
@cross_origin()
def addCustomer():
    """
    An API that adds a new customer 
    ---
    parameters:
       - name: firstName
         in: request
         type: string
         required: false   
       - name: lastName
         in: request
         type: string
         required: false   
       - name: emailId
         in: request
         type: string
         required: false   
       - name: mobileNumber
         in: request
         type: int
         required: false   
       - name: address
         in: request
         type: string
         required: false      
       - name: zipcode
         in: request
         type: int
         required: false                                                     
    responses:
        200:
            description: Successfully added a customer
            schema:
                id: id
                properties:
                    id:
                        type: int
                        description: Autogenerated id of the customer
                        default: None                
    """        
    data = request.get_json()
    firstName = data.get('firstName', '')
    lastName = data.get('lastName', '')
    address = data.get('address', '')
    zipCode = data.get('zipCode', '')
    emailId = data.get('emailId', '')
    mobileNumber = data.get('mobileNumber', '')

    customerId = customerDomain.addCustomer(
        firstName, lastName, address, zipCode, emailId, mobileNumber)

    return {'id': customerId}, 201
